spring:
  application:
    name: person-service
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/persons}
    password: ${SPRING_R2DBC_PASSWORD:test}
    username: ${SPRING_R2DBC_USERNAME:program}
  webflux:
    base-path: /api/v1
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      springframework:
        web: debug
        r2dbc: debug

server:
  port: ${PORT:8080}
