name: GitHub Build Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Wait for Render deployment to be ready
        run: |
          RENDER_URL="${{ secrets.RENDER_URL }}"
          echo "Waiting for Render deployment: $RENDER_URL"
          
          # Пытаемся сделать health check каждые 10 секунд в течение 3 минут
          for i in {1..30}; do
           if curl -f -s "$RENDER_URL/health" > /dev/null; then
             echo "Render app is ready!"
             break
           else
             echo "⏳ Attempt $i: Render app not ready yet, waiting 10 seconds..."
             sleep 10
           fi
          
           if [ $i -eq 30 ]; then
             echo "ERROR Render app did not become ready in time"
             exit 1
           fi
          done

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'